services:
  db:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: Asia/Bangkok
    ports:
      - "4042:5432"   # เปิดถ้าต้องเข้า psql จากข้างนอก, ไม่จำเป็นก็เอาออกได้
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/db-init:/docker-entrypoint-initdb.d:ro   # มีสคริปต์ init/extension อยู่แล้ว
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    restart: unless-stopped

  redis:
    image: redis:7.4.5
    command: >
      sh -lc 'redis-server --appendonly yes --save 60 1000 --requirepass "$${REDIS_PASSWORD}"'
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-404Redis}
      REDIS_URL: ${REDIS_URL:-redis://default:${REDIS_PASSWORD:-404Redis}@redis:6379}
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a ${REDIS_PASSWORD} ping | grep PONG"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s
    restart: unless-stopped

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
      target: prod
    environment:
      NODE_ENV: production
      PORT: ${PORT}
            # DB (อย่าใช้ localhost ใช้ชื่อ service)
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      DB_HOST: ${DB_HOST}  
      DB_PORT: ${DB_PORT}
      DATABASE_URL: ${DATABASE_URL}

      # Redis
      REDIS_PASSWORD: ${REDIS_PASSWORD:-404Redis}
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_URL: redis://default:${REDIS_PASSWORD:-404Redis}@${REDIS_HOST:-redis}:${REDIS_PORT:-6379}

      PRISMA_SCHEMA_PATH: ./src/infrastructure/database/prisma/schema.prisma
      PRISMA_GENERATE: "false"           # generate ตอน build แล้ว
      RUN_MIGRATIONS: "true"             # ให้ entrypoint รัน Prisma
      PRISMA_STRATEGY: migrate-deploy     # ใช้ migrations แบบ production
      START_CMD: "node dist/main.js"      # รันไฟล์ build แล้ว
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "4041:4044"
    restart: unless-stopped

volumes:
  pgdata:
  redis_data:
